jekyll serve --watch --baseurl ""markdown: redcarpet
collections: 
  - neat_people
baseurl: prettyneat.io
exclude: ["README.md"]
permalink: /:title/
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-analytics
jekyll_analytics:
  GoogleAnalytics: # Add, if you want to track with Google Analytics
    id: UA-159943696-1 # Required - replace with your tracking id
    anonymizeIp: false # Optional - Default: false - set to true for anonymized tracking
